#cloud-config

coreos:
  units:
    - name: kube-env.service
      command: start
      content: |
        [Unit]
        Description=Fetch kubernetes-node-environment
        Requires=network-online.target
        After=network-online.target
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/curl --fail --silent --show-error \
        -H "X-Google-Metadata-Request: True" \
        -o /etc/kube-env \
        http://metadata.google.internal/computeMetadata/v1/instance/attributes/kube-env

    - name: kubernetes-install-rkt.service
      command: start
      content: |
        [Unit]
        Description=Fetch Rocket
        Documentation=http://github.com/coreos/rkt
        Requires=network-online.target
        After=network-online.target
        [Service]
        EnvironmentFile=/etc/kube-env
        ExecStartPre=/usr/bin/mkdir -p /opt/rkt
        ExecStartPre=/usr/bin/wget \
        -O /opt/rkt/rkt-v0.5.4.tar.gz \
        https://github.com/coreos/rkt/releases/download/v0.5.4/rkt-v0.5.4.tar.gz
        ExecStart=/usr/bin/tar xzvf /opt/rkt/rkt-v0.5.4.tar.gz -C /opt --overwrite
        
    - name: kubernetes-install-minion.service
      command: start
      content: |
        [Unit]
        Description=Install Kubernetes Server
        Requires=network-online.target
        After=network-online.target
        Requires=kube-env.service
        After=kube-env.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/kube-env
        ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes/pkg
        ExecStartPre=/usr/bin/curl --location --create-dirs --output /opt/kubernetes/pkg/kubernetes-server-linux-amd64.tar.gz ${SERVER_BINARY_TAR_URL}
        ExecStart=/usr/bin/tar xf /opt/kubernetes/pkg/kubernetes-server-linux-amd64.tar.gz -C /opt --overwrite

    # TODO: This is totally hacky. salt tarball is required for generate cert and master components
    # manifest
    - name: kube-install-salt.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Salt Based Configuration Fetcher
        Requires=network-online.target
        After=network-online.target
        Requires=kube-env.service
        After=kube-env.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/kube-env
        ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes/salt
        ExecStartPre=/usr/bin/curl --location --create-dirs --output /opt/kubernetes/salt/kubernetes-salt.tar.gz ${SALT_TAR_URL}
        ExecStart=/usr/bin/tar xf /opt/kubernetes/salt/kubernetes-salt.tar.gz -C /opt --overwrite

    - name: kube-install-cert.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Cert Installer
        Requires=network-online.target
        After=network-online.target
        Requires=kube-env.service
        After=kube-env.service
        Requires=kube-install-salt.service
        After=kube-install-salt.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/kube-env
        ExecStartPre=/sbin/groupadd kube-cert
        ExecStart=/opt/kubernetes/saltbase/salt/generate-cert/make-ca-cert.sh _use_gce_external_ip_ --overwrite

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubelet
        Requires=kubernetes-install-minion.service
        After=kubernetes-install-minion.service
        Requires=kubernetes-install-rkt.service
        After=kubernetes-install-rkt.service
        [Service]
        EnvironmentFile=/etc/kube-env
        ExecStart=/opt/kubernetes/server/bin/kubelet \
        --api_servers=https://kubernetes-master.c.golden-system-455.internal \
        --config=/etc/kubernetes/manifests \
        --allow_privileged=False \
        --v=2 \
        --cluster_dns=10.0.0.10 \
        --cluster_domain=kubernetes.local \
        --logtostderr=true

    - name: kube-proxy.service
      command: start
      content: |
        [Unit]
        Description=Kube-proxy
        Requires=kubernetes-install-minion.service
        After=kubernetes-install-minion.service
        Requires=kubernetes-install-rkt.service
        After=kubernetes-install-rkt.service
        [Service]
        EnvironmentFile=/etc/kube-env
        ExecStart=/opt/kubernetes/server/bin/kube-proxy \
        --master=http://kubernetes-master.c.golden-system-455.internal:7080 \
        --v=2 \
        --logtostderr=true
